function Add_Annotation_toPhasecurrent(linewidth, font_size)
% %绘制竖线
% annotation('line',[0.385 0.385],[0.13 0.98],...
%     'LineWidth',linewidth/2,...
%     'LineStyle','--');
% annotation('line',[0.607 0.607],[0.13 0.98],...
%     'LineWidth',linewidth/2, ...
%     'LineStyle','--');
% 
% %绘制箭头
% annotation('doublearrow',[0.1 0.385],[0.62 0.62],'LineWidth',linewidth/2,...
%     'Head1Width',2, ...
%     'Head2Width',2, ...
%     'Head1Length',4, ...
%     'Head2Length',4);
% annotation('doublearrow',[0.385 0.607],[0.62 0.62],'LineWidth',linewidth/2,...
%     'Head1Width',2, ...
%     'Head2Width',2, ...
%     'Head1Length',4, ...
%     'Head2Length',4);
% annotation('doublearrow',[0.607 0.95],[0.62 0.62],'LineWidth',linewidth/2, ...
%     'Head1Width',2, ...
%     'Head2Width',2, ...
%     'Head1Length',4, ...
%     'Head2Length',4);
% 
% %添加文本标注
% annotation('textbox',...
%     [0.17 0.64 0.17 0.031],...
%     'VerticalAlignment','middle',...
%     'String','Heathy',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'FontSize',font_size,...
%     'FontName','Times New Roman',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% annotation('textbox',...
%     [0.43 0.64 0.17 0.031],...
%     'VerticalAlignment','middle',...
%     'String','Fault',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'FontSize',font_size,...
%     'FontName','Times New Roman',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% annotation('textbox',...
%     [0.71 0.64 0.17 0.031],...
%     'VerticalAlignment','middle',...
%     'String','Fault-tolerant',...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'FontSize',font_size,...
%     'FontName','Times New Roman',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');

%%添加电流标注
annotation('textbox',...
    [0.954 0.173 0.028 0.084],...
    'VerticalAlignment','middle',...
    'String','\boldmath{$i_e$}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',font_size,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% 创建 textbox
annotation('textbox',...
    [0.954 0.342 0.028 0.084],...
    'VerticalAlignment','middle',...
    'String','\boldmath{$i_d$}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',font_size,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% 创建 textbox
annotation('textbox',...
    [0.954 0.854 0.028 0.084],...
    'VerticalAlignment','middle',...
    'String','\boldmath{$i_a$}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',font_size,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% 创建 textbox
annotation('textbox',...
    [0.954 0.684 0.028 0.084],...
    'VerticalAlignment','middle',...
    'String','\boldmath{$i_b$}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',font_size,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');

% 创建 textbox
annotation('textbox',...
    [0.954 0.515 0.028 0.084],...
    'VerticalAlignment','middle',...
    'String','\boldmath{$i_c$}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',font_size,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'EdgeColor','none');
end