%% 开始绘制电流波形
function [fig,out_ps,out_mm] = plotCurrentWaveform(in_ps, in_mm)
    fig=figure;
    set(fig,'Units',in_ps.CurrentFigParams.Units,'position', ...
        [3 3 in_ps.CurrentFigParams.Width in_ps.CurrentFigParams.Height],'Resize',1);
    in_ps.CurrentFigParams.InnerPostion=get(fig, 'Position');
    in_ps.CurrentFigParams.OuterPostion=get(fig, 'OuterPosition');
    ax=axes('position',[0.11 0.22 0.85 0.75]);
    
    in_mm.DataName=fieldnames(in_mm.Data)';


    for i=1:1
        plot(ax,in_mm.Data.(in_mm.DataName{1})([in_ps.Current.StartPoint:1:in_ps.Current.EndPoint],1), ...
            in_mm.Data.(in_mm.DataName{4+i})([in_ps.Current.StartPoint:1:in_ps.Current.EndPoint],1), ...
            'color',in_ps.CurrentFigParams.Color(i),...
            'LineWidth',in_ps.CurrentFigParams.LineWidth);
        in_mm.Maxcurrent(i)=max(in_mm.Data.(in_mm.DataName{4+i})([in_ps.Current.StartPoint:in_ps.Current.EndPoint],1));
        hold on
    end
    set(ax,'FontName','Times New Roman', ...
        'FontSize',in_ps.CurrentFigParams.FontSize, ...
        'FontWeight','bold', ...
        'GridLineStyle','--', ...
        'LineWidth',0.9, ...
        'GridAlpha',0.2);
    set(ax,'Xlim',in_ps.CurrentFigParams.Xlim);
    set(ax,'Ylim',[-in_ps.CurrentFigParams.YZoomin*max(in_mm.Maxcurrent), ...
                    in_ps.CurrentFigParams.YZoomin*max(in_mm.Maxcurrent)]);
    % 计算总跨度（以毫秒为单位）
    totalSpan = (in_ps.CurrentFigParams.Xlim(2) - in_ps.CurrentFigParams.Xlim(1)) * 1000; % 转换为毫秒
    
    % 计算间隔（平均分成4部分）
    interval = totalSpan / 4;
    
    % 生成 x 轴的标签
    xt = 0:interval:totalSpan;
    xtls = string(arrayfun(@num2str, xt, 'UniformOutput', false));
    xt=xt/1000+in_ps.CurrentFigParams.Xlim(1);% 将标记转换回秒
    set(ax, 'XTick', xt); 
    set(ax, 'XTickLabel', xtls);
    set(ax,'XGrid','on');
    set(ax,'YGrid','on');
    xlabel(ax,'Time(ms)', ...
        'Units','normalized', ...
        'Position',[0.5 -0.2], ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontWeight','bold',...
        'FontSize',in_ps.CurrentFigParams.FontSize);
    ylabel(ax,'Phase Current(A)', ...
        'Units','normalized', ...
        'Position',[-0.10 0.5], ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontWeight','bold',...
        'FontSize',in_ps.CurrentFigParams.FontSize);
    leg1=legend(ax,'\boldmath{$i_a$}','\boldmath{$i_b$}','\boldmath{$i_c$}', ...
        '\boldmath{$i_d$}','\boldmath{$i_e$}', ...
        'Interpreter','latex', ...
        'Location','northeast', ...
        'AutoUpdate','off', ...
        'FontName','Times New Roman', ...
        'FontSize',8, ...
        'Orientation','horizontal', ...
        'Box','off');
    leg1.ItemTokenSize=[10,10];
%     % 创建 line
% annotation(fig,'line',[0.45 0.45],...
%     [0.229 0.981],...
%     'Color',[0.15 0.15 0.15],...
%     'LineWidth',1,...
%     'LineStyle','--');
% 
% % 创建 line
% annotation(fig,'line',[0.3 0.3],...
%     [0.229 0.981],...
%     'Color',[0.15 0.15 0.15],...
%     'LineWidth',1,...
%     'LineStyle','--');
% 
% % 创建 textbox
% annotation(fig,'textbox',...
%     [0.129306878306876 0.222222220203861 0.175925929331906 0.150793652812009],...
%     'String','Heathy',...
%     'FontWeight','bold',...
%     'FontSize',8,...
%     'FontName','Times New Roman',...
%     'EdgeColor','none');
% 
% % 创建 textbox
% annotation(fig,'textbox',...
%     [0.57242857142857 0.224867722849366 0.276455032257806 0.150793652812009],...
%     'String','Fault-tolerant',...
%     'FontWeight','bold',...
%     'FontSize',8,...
%     'FontName','Times New Roman',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');
% 
% % 创建 textbox
% annotation(fig,'textbox',...
%     [0.315814814814811 0.220899468881109 0.146825399537566 0.150793652812009],...
%     'String','Fault',...
%     'FontWeight','bold',...
%     'FontSize',8,...
%     'FontName','Times New Roman',...
%     'EdgeColor','none');
    out_ps=in_ps;
    out_mm=in_mm;

end