function Fig1=Plot_FivephaseCurrent(Pic_Width, Pic_Height, MotorCurrent, ...
    Start_Point, End_Point, linewidth, ...
    Start_Time, End_Time, YZoomin, font_size)

Fig1=figure;
set(Fig1,'Units','centimeters','position',[0 0 Pic_Width Pic_Height]);

ax1=subplot(5,1,1);
plot(ax1,MotorCurrent.time((Start_Point:1:End_Point),:),...
     MotorCurrent.a((Start_Point:1:End_Point),:), ...
     'color','#e74c3c', ...
     'LineWidth',linewidth);
xticks(ax1,[Start_Time,(End_Time-Start_Time)/4+Start_Time,(End_Time-Start_Time) ...
    *2/4+Start_Time,(End_Time-Start_Time)*3/4+Start_Time,End_Time]);
xticklabels({});
set(ax1,'Ylim',[-YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:)), ...
                YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:))]);
set(ax1,'Xlim',[Start_Time,End_Time]);
set(ax1,'FontName','Times New Roman','FontSize',font_size,'FontWeight','bold');
set(ax1,'XGrid','on');
set(ax1,'YGrid','on');
set(ax1,'Units','normalized','position',[0.1 0.81 0.85 0.17]);

ax2=subplot(5,1,2);
plot(ax2,MotorCurrent.time((Start_Point:1:End_Point),:),...
     MotorCurrent.b((Start_Point:1:End_Point),:), ...
     'color','#2980b9', ...
     'LineWidth',linewidth);
xticks(ax2,[Start_Time,(End_Time-Start_Time)/4+Start_Time,(End_Time-Start_Time) ...
    *2/4+Start_Time,(End_Time-Start_Time)*3/4+Start_Time,End_Time]);
xticklabels({});
set(ax2,'Ylim',[-YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:)), ...
                YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:))]);
set(ax2,'Xlim',[Start_Time,End_Time]);
set(ax2,'FontName','Times New Roman','FontSize',font_size,'FontWeight','bold');
set(ax2,'XGrid','on');
set(ax2,'YGrid','on');
set(ax2,'Units','normalized','position',[0.1 0.64 0.85 0.17]);

ax3=subplot(5,1,3);
plot(ax3,MotorCurrent.time((Start_Point:1:End_Point),:),...
     MotorCurrent.c((Start_Point:1:End_Point),:), ...
     'color','#2980b9', ...
     'LineWidth',linewidth);
xticks(ax3,[Start_Time,(End_Time-Start_Time)/4+Start_Time, ...
    (End_Time-Start_Time)*2/4+Start_Time,...
    (End_Time-Start_Time)*3/4+Start_Time,End_Time]);
xticklabels({});
ylabel(ax3,'Phase Current(A)','Units','normalized','Position',[-0.08 0.5], ...
    'HorizontalAlignment','center','VerticalAlignment','middle');
set(ax3,'Ylim',[-YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:)), ...
                YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:))]);
set(ax3,'Xlim',[Start_Time,End_Time]);
set(ax3,'FontName','Times New Roman','FontSize',font_size,'FontWeight','bold');
set(ax3,'XGrid','on');
set(ax3,'YGrid','on');
set(ax3,'Units','normalized','position',[0.1 0.47 0.85 0.17]);

ax4=subplot(5,1,4);
plot(ax4,MotorCurrent.time((Start_Point:1:End_Point),:),...
     MotorCurrent.d((Start_Point:1:End_Point),:), ...
     'color','#8e44ad', ...
     'LineWidth',linewidth);
xticks(ax4,[Start_Time,(End_Time-Start_Time)/4+Start_Time, ...
    (End_Time-Start_Time)*2/4+Start_Time,...
    (End_Time-Start_Time)*3/4+Start_Time,End_Time]);
xticklabels({});
set(ax4,'Xlim',[Start_Time,End_Time]);
set(ax4,'Ylim',[-YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:)), ...
                YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:))]);
set(ax4,'FontName','Times New Roman','FontSize',font_size,'FontWeight','bold');
set(ax4,'XGrid','on');
set(ax4,'YGrid','on');
set(ax4,'Units','normalized','position',[0.1 0.3 0.85 0.17]);

ax5=subplot(5,1,5);
plot(ax5,MotorCurrent.time((Start_Point:1:End_Point),:),...
     MotorCurrent.d((Start_Point:1:End_Point),:), ...
     'color','#f39c12', ...
     'LineWidth',linewidth);
xticks(ax5,[Start_Time,(End_Time-Start_Time)/4+Start_Time, ...
    (End_Time-Start_Time)*2/4+Start_Time,...
    (End_Time-Start_Time)*3/4+Start_Time,End_Time]);
xticklabels(ax5,{'0','50','100','150','200'});
set(ax5,'Xlim',[Start_Time,End_Time]);
set(ax5,'Ylim',[-YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:)), ...
                YZoomin*max(MotorCurrent.a((Start_Point:1:End_Point),:))]);
set(ax5,'FontName','Times New Roman','FontSize',font_size,'FontWeight','bold');
set(ax5,'XGrid','on');
set(ax5,'YGrid','on');
set(ax5,'Units','normalized','position',[0.1 0.13 0.85 0.17]);
xlabel(ax5,'Time(ms)','Units','normalized','Position',[0.5 -0.52], ...
    'HorizontalAlignment','center','VerticalAlignment','middle');

end